services:
  couchdb:
    image: couchdb:3
    restart: unless-stopped
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: admin
    ports:
      - "5984:5984"
    volumes:
      - couch_data:/opt/couchdb/data

  front:
    build: .
    restart: unless-stopped
    depends_on:
      - couchdb
    ports:
      - "8080:80"

volumes:
  couch_data:
